### ISSUE TITLE
AnswerFriendRequest doesn't remove request when answered 

### ISSUE THREAD

**Issue by ChristosTanailidis** [Lemas97/Sousou-Api#19]
When `AnswerFriendRequest` is executed the requests remains

**Comment by ChristosTanailidis** [comment]
Also `AnswerFriendRequest` always throws errors

![image](https://user-images.githubusercontent.com/32941481/185808162-988e9224-0b1f-45bd-b746-bf76bcc1d07d.png)

**Comment by Lemas97** [comment]
> Also `AnswerFriendRequest` always throws errors
> 
> ![image](https://user-images.githubusercontent.com/32941481/185808162-988e9224-0b1f-45bd-b746-bf76bcc1d07d.png)

Because users are already friends
